### ISSUE TITLE
Province ID irregularities

### ISSUE THREAD

**Issue by ErdaradunGaztea** [AlejandroGiner/Lux-in-Tenebris#11]
I tried to translate some of the Polish names for provinces. To verify in-game placement of each province I used `debug_mode` and hovered the pointer over provinces I wanted to check. Simultaneously I had that whole list of translations imported to R so that I could sort them and filter interesting rows.

However, in-game IDs were different to those I found in the files in this repository. Now, the question is – which ones are the correct ones? For example: Tesinsko province. In-game its ID is 4742, `map/positions.txt` has comment with 3606, `history/provinces/` folder has file `3606 - Tesinsko.txt` with first-line comment `#4742 - Tesinsko` and `common/province_names/polish.txt` has `3606 = "Cieszyn"`. What's more, if I assimilate this (4742) province as Poland, it correctly changes its name to "Cieszyn". On the other hand, province 3606 doesn't even exist.

Yes, I use the latest Steam version of this mod and 1.29.6 version of EU4 in English with dynamic province names turned on.

What's going on here and what should I edit and with which IDs to translate more province names?

**Comment by Narediel** [comment]
Hello @MatiFilozof 

Sorry for answering late, I don't understand github well and thought it was a contribution/fork or something, not an issue/question.

The reason there's these province ID irregularities is because prior to 1.30 (like in the Steam 1.29.6 version) Tesinsko was 4742, but after 1.30 4742 was in use by a vanilla province, in this case 4742 - Goslar. So what I did was move Tesinsko to another ID not conflicting with vanilla (3606 in this case), and use 4742 for the proper vanilla equivalent.

The correct IDs are the ones currently in use in the Github master version, which is properly adapted for 1.30 IDs.
Cheers

**Comment by ErdaradunGaztea** [comment]
Thanks, that explains everything, I think. No worries about answering late, I really didn't need immediate reply, why would I even?
